apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pulsenet-secrets
  namespace: pulsenet
  labels:
    app.kubernetes.io/name: pulsenet
    app.kubernetes.io/part-of: pulsenet-rul-forecasting
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pulsenet-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      metadata:
        labels:
          app.kubernetes.io/name: pulsenet
      data:
        PULSENET_JWT_SECRET: "{{ .jwt_secret }}"
        PULSENET_ENCRYPTION_KEY: "{{ .encryption_key }}"
        PULSENET_USERS: "{{ .users_json }}"
        PULSENET_MLFLOW_TRACKING_PASSWORD: "{{ .mlflow_password }}"
        PULSENET_ARTIFACT_MANIFEST_KEY: "{{ .artifact_manifest_key }}"
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: pulsenet/production/secrets
        property: jwt_secret
    - secretKey: encryption_key
      remoteRef:
        key: pulsenet/production/secrets
        property: encryption_key
    - secretKey: users_json
      remoteRef:
        key: pulsenet/production/secrets
        property: users_json
    - secretKey: mlflow_password
      remoteRef:
        key: pulsenet/production/secrets
        property: mlflow_password
    - secretKey: artifact_manifest_key
      remoteRef:
        key: pulsenet/production/secrets
        property: artifact_manifest_key
