apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulsenet-sa
  namespace: pulsenet
  labels:
    app.kubernetes.io/name: pulsenet
    app.kubernetes.io/part-of: pulsenet-rul-forecasting
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulsenet-role
  namespace: pulsenet
  labels:
    app.kubernetes.io/name: pulsenet
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulsenet-role-binding
  namespace: pulsenet
  labels:
    app.kubernetes.io/name: pulsenet
subjects:
  - kind: ServiceAccount
    name: pulsenet-sa
    namespace: pulsenet
roleRef:
  kind: Role
  name: pulsenet-role
  apiGroup: rbac.authorization.k8s.io
