#!/usr/bin/env python3
"""
Generate a small synthetic FIXTURE in NASA C-MAPSS FD001 format.

PURPOSE
-------
Lets contributors run `python main_pipeline.py --mode full` end-to-end
without first downloading the full ~12 MB NASA dataset. The output is
**clearly labeled fixture data**, never used for benchmark numbers — those
must come from running the suite against the real C-MAPSS dataset.

The C-MAPSS FD001 row format is documented at:
    https://data.nasa.gov/dataset/cmapss-jet-engine-simulated-data
26 whitespace-separated columns:
    unit_id, cycle, op_setting_1, op_setting_2, op_setting_3, sensor_1..21

USAGE
-----
    python scripts/generate_test_fixture.py --out data/

This writes data/train_FD001.txt, data/test_FD001.txt, data/RUL_FD001.txt
with 5 engines each, ~50-150 cycles per engine. Marked clearly as fixture.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

# Per FD001 documentation:
N_OP_SETTINGS = 3
N_SENSORS = 21
N_COLUMNS = 2 + N_OP_SETTINGS + N_SENSORS  # 26

# Realistic per-sensor baselines from the FD001 documentation header
# (these are healthy-engine starting values, not synthetic guesses).
HEALTHY_BASELINE = {
    1: 518.67, 2: 642.0, 3: 1589.7, 4: 1400.6, 5: 14.62,
    6: 21.61, 7: 554.4, 8: 2388.0, 9: 9046.2, 10: 1.30,
    11: 47.2, 12: 521.7, 13: 2388.0, 14: 8138.6, 15: 8.42,
    16: 0.03, 17: 392, 18: 2388, 19: 100.0, 20: 38.9, 21: 23.4,
}


def _generate_engine(unit_id: int, cycles: int, rng: np.random.Generator) -> np.ndarray:
    """One engine's run-to-failure trace shaped like FD001."""
    rows = np.zeros((cycles, N_COLUMNS), dtype=np.float64)
    rows[:, 0] = unit_id
    rows[:, 1] = np.arange(1, cycles + 1)
    # op_settings (cols 2-4): mostly constant for FD001 (sea-level)
    rows[:, 2] = rng.normal(0.0, 0.001, cycles)
    rows[:, 3] = rng.normal(0.0, 0.001, cycles)
    rows[:, 4] = 100.0  # FD001 fault mode marker
    # sensors (cols 5-25): healthy baseline + small noise + linear drift on a few
    drift_progress = np.linspace(0, 1, cycles)
    for i in range(1, N_SENSORS + 1):
        col = 4 + i
        baseline = HEALTHY_BASELINE[i]
        noise = rng.normal(0, abs(baseline) * 0.001, cycles)
        # only sensors known to drift in FD001 get drift
        drift = drift_progress * abs(baseline) * 0.005 if i in (2, 3, 4, 7, 11, 12, 15, 17, 21) else 0.0
        rows[:, col] = baseline + noise + drift
    return rows


def generate_fixture(out_dir: Path, n_engines: int = 5, seed: int = 42) -> None:
    """Write fixture train/test/RUL files in C-MAPSS FD001 format."""
    rng = np.random.default_rng(seed)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Train engines: full run-to-failure (varying lengths)
    train_rows = []
    for unit in range(1, n_engines + 1):
        cycles = int(rng.integers(120, 200))
        train_rows.append(_generate_engine(unit, cycles, rng))
    train = np.vstack(train_rows)

    # Test engines: truncated traces (engine still running)
    test_rows = []
    rul_remaining = []
    for unit in range(1, n_engines + 1):
        full_cycles = int(rng.integers(150, 250))
        truncate_at = int(rng.integers(50, full_cycles - 30))
        test_rows.append(_generate_engine(unit, truncate_at, rng))
        rul_remaining.append(full_cycles - truncate_at)
    test = np.vstack(test_rows)

    # Format: integers for unit/cycle, floats for the rest
    def _fmt_row(r: np.ndarray) -> str:
        ints = f"{int(r[0])} {int(r[1])}"
        floats = " ".join(f"{v:.4f}" for v in r[2:])
        return f"{ints} {floats}"

    train_path = out_dir / "train_FD001.txt"
    test_path = out_dir / "test_FD001.txt"
    rul_path = out_dir / "RUL_FD001.txt"

    with train_path.open("w") as f:
        for row in train:
            f.write(_fmt_row(row) + "\n")
    with test_path.open("w") as f:
        for row in test:
            f.write(_fmt_row(row) + "\n")
    with rul_path.open("w") as f:
        for r in rul_remaining:
            f.write(f"{r}\n")

    # Also write a README inside data/ so nobody mistakes this for the real dataset.
    (out_dir / "FIXTURE_README.txt").write_text(
        "PULSENET TEST FIXTURE — NOT REAL C-MAPSS DATA\n"
        "==============================================\n"
        f"Generated by scripts/generate_test_fixture.py (seed={seed}).\n"
        f"Format: NASA C-MAPSS FD001 (26 cols, whitespace-separated).\n"
        f"Engines: {n_engines} train + {n_engines} test.\n\n"
        "This fixture exists only so contributors can run the pipeline\n"
        "end-to-end without downloading the real dataset. ANY benchmark\n"
        "numbers produced from this fixture are MEANINGLESS — replace\n"
        "with the real dataset before reporting results.\n\n"
        "Real dataset: https://data.nasa.gov/dataset/cmapss-jet-engine-simulated-data\n"
    )

    print(f"Wrote fixture to {out_dir}/")
    print(f"  train_FD001.txt  ({len(train)} rows, {n_engines} engines)")
    print(f"  test_FD001.txt   ({len(test)} rows, {n_engines} engines)")
    print(f"  RUL_FD001.txt    ({len(rul_remaining)} rows)")
    print(f"  FIXTURE_README.txt — read this before drawing conclusions")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("data"),
                        help="Output directory (default: ./data)")
    parser.add_argument("--engines", type=int, default=5,
                        help="Number of engines (default: 5)")
    parser.add_argument("--seed", type=int, default=42,
                        help="RNG seed (default: 42)")
    args = parser.parse_args()
    generate_fixture(args.out, args.engines, args.seed)


if __name__ == "__main__":
    main()
